"""
export_weights.py — Convert a trained PortraitGAN generator checkpoint
into a JavaScript-embeddable base64 Float32Array literal.

Usage:
    # Full float32 export (~15 MB JS string):
    python export/export_weights.py \
        --checkpoint run/checkpoints/generator_final.pth \
        --output inference/weights_b64.js

    # Int8 quantized export (~4 MB JS string, slight quality loss):
    python export/export_weights.py \
        --checkpoint run/checkpoints/generator_final.pth \
        --output inference/weights_b64.js \
        --quantize int8

    # Then build final HTML:
    python export/build_html.py \
        --weights inference/weights_b64.js \
        --output docs/portrait_gan.html

Output format (weights_b64.js):
    // Auto-generated by export_weights.py
    // Generator: 3,812,099 parameters | float32 | 14.5 MB raw | 4.2 MB quantized
    const MODEL_METADATA = { ... };
    const WEIGHTS_B64 = "...base64 string...";
    const QUANT_SCALE = [...];   // only if quantized
    const QUANT_ZERO  = [...];   // only if quantized
"""

import os
import sys
import json
import struct
import base64
import argparse
from pathlib import Path
from collections import OrderedDict

import torch
import numpy as np

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))
from src.model import Generator, NZ, IMG_SIZE
from src.labels import DIM_SIZES, EMBED_DIM_PER_DIM, CONDITION_DIM, NUM_DIMS


# ─────────────────────────────────────────────────────────────────────────────
# WEIGHT EXTRACTION
# ─────────────────────────────────────────────────────────────────────────────

def extract_generator_weights(checkpoint_path: str, use_ema: bool = True) -> dict:
    """
    Load a checkpoint and return the generator's state_dict.
    Prefers the EMA weights if available (better quality).
    """
    ckpt = torch.load(checkpoint_path, map_location="cpu")

    # Try EMA first, fall back to raw generator
    if use_ema and "G_ema" in ckpt:
        print(f"  Using EMA weights (better quality)")
        state = ckpt["G_ema"]
    elif "G" in ckpt:
        print(f"  Using raw generator weights")
        state = ckpt["G"]
    elif "state_dict" in ckpt:
        state = ckpt["state_dict"]
    else:
        # The checkpoint IS the state dict
        state = ckpt

    # Build the model and verify it loads cleanly
    G = Generator()
    missing, unexpected = G.load_state_dict(state, strict=False)
    if missing:
        print(f"  [WARN] Missing keys: {missing[:5]}{'...' if len(missing)>5 else ''}")
    if unexpected:
        print(f"  [WARN] Unexpected keys: {unexpected[:5]}{'...' if len(unexpected)>5 else ''}")

    return G, state


# ─────────────────────────────────────────────────────────────────────────────
# FLOAT32 EXPORT
# ─────────────────────────────────────────────────────────────────────────────

def export_float32(state_dict: dict) -> tuple:
    """
    Flatten all parameters into a single Float32Array.
    Returns (flat_array, param_layout) where param_layout maps
    param names → (offset, shape) for reconstruction in JS.
    """
    param_layout = OrderedDict()
    offset = 0
    arrays = []

    for name, tensor in state_dict.items():
        if not isinstance(tensor, torch.Tensor):
            continue
        arr = tensor.float().detach().cpu().numpy().flatten()
        param_layout[name] = {
            "offset": offset,
            "shape": list(tensor.shape),
            "numel": arr.size,
        }
        arrays.append(arr)
        offset += arr.size

    flat = np.concatenate(arrays).astype(np.float32)
    return flat, param_layout


# ─────────────────────────────────────────────────────────────────────────────
# INT8 QUANTIZATION
# ─────────────────────────────────────────────────────────────────────────────

def quantize_int8(flat: np.ndarray, block_size: int = 128) -> tuple:
    """
    Per-block symmetric int8 quantization.
    Divides weights into blocks of `block_size`, finds the max absolute value
    per block, and maps [-max, +max] → [-127, +127].

    Returns:
        quantized  — int8 array, same length as flat
        scales     — float32 array, one scale per block
        zero_points— all zeros (symmetric quantization)
    """
    n = len(flat)
    n_blocks = (n + block_size - 1) // block_size

    # Pad to multiple of block_size
    padded = np.zeros(n_blocks * block_size, dtype=np.float32)
    padded[:n] = flat

    blocks = padded.reshape(n_blocks, block_size)
    max_abs = np.abs(blocks).max(axis=1, keepdims=True)
    max_abs = np.where(max_abs == 0, 1.0, max_abs)  # avoid div by zero

    scales = max_abs.squeeze().astype(np.float32)
    quantized = np.clip(
        np.round(blocks / max_abs * 127), -127, 127
    ).astype(np.int8)

    return quantized.flatten()[:n], scales


def dequantize_int8(quantized: np.ndarray, scales: np.ndarray,
                    original_len: int, block_size: int = 128) -> np.ndarray:
    """Verify round-trip: dequantize back to float32."""
    n_blocks = len(scales)
    padded = np.zeros(n_blocks * block_size, dtype=np.float32)
    q_padded = np.zeros(n_blocks * block_size, dtype=np.int8)
    q_padded[:len(quantized)] = quantized

    blocks = q_padded.reshape(n_blocks, block_size).astype(np.float32)
    blocks *= (scales / 127.0).reshape(-1, 1)
    padded = blocks.flatten()
    return padded[:original_len]


# ─────────────────────────────────────────────────────────────────────────────
# JS FILE WRITER
# ─────────────────────────────────────────────────────────────────────────────

def write_js_float32(flat: np.ndarray, param_layout: dict,
                     output_path: str, metadata: dict):
    """Write float32 weights as a base64-encoded JS file."""
    raw_bytes = flat.tobytes()
    b64 = base64.b64encode(raw_bytes).decode("ascii")

    raw_mb  = len(raw_bytes) / (1024**2)
    b64_mb  = len(b64) / (1024**2)

    print(f"  Parameters:  {flat.size:,}")
    print(f"  Raw size:    {raw_mb:.1f} MB (float32)")
    print(f"  Base64 size: {b64_mb:.1f} MB")

    metadata.update({
        "dtype": "float32",
        "n_params": int(flat.size),
        "raw_mb": round(raw_mb, 2),
        "b64_mb": round(b64_mb, 2),
        "quantized": False,
    })

    layout_json = json.dumps(param_layout, indent=None, separators=(',', ':'))
    meta_json   = json.dumps(metadata, indent=2)

    js = f"""// PortraitGAN Generator Weights — Float32
// Auto-generated by export/export_weights.py
// DO NOT EDIT MANUALLY
//
// Parameters: {flat.size:,}
// Raw size:   {raw_mb:.1f} MB
// Base64 size:{b64_mb:.1f} MB

const MODEL_METADATA = {meta_json};

const PARAM_LAYOUT = {layout_json};

// All generator weights flattened to a single Float32Array
// Decode: Float32Array from base64 → use PARAM_LAYOUT to slice
const WEIGHTS_B64 = "{b64}";
"""
    with open(output_path, "w") as f:
        f.write(js)
    print(f"  Written → {output_path}")


def write_js_int8(flat_original: np.ndarray, quantized: np.ndarray,
                  scales: np.ndarray, param_layout: dict,
                  output_path: str, metadata: dict):
    """Write int8-quantized weights as a base64-encoded JS file."""
    # Verify quality
    deq = dequantize_int8(quantized, scales, len(flat_original))
    mse = np.mean((flat_original - deq) ** 2)
    snr = 10 * np.log10(np.mean(flat_original**2) / (mse + 1e-10))
    print(f"  Quantization SNR: {snr:.1f} dB  (>30 dB = good, >40 dB = excellent)")

    q_bytes    = quantized.tobytes()
    scale_bytes = scales.astype(np.float32).tobytes()

    q_b64     = base64.b64encode(q_bytes).decode("ascii")
    scale_b64 = base64.b64encode(scale_bytes).decode("ascii")

    raw_mb_fp32 = len(flat_original) * 4 / (1024**2)
    q_mb        = len(q_bytes) / (1024**2)
    total_b64   = (len(q_b64) + len(scale_b64)) / (1024**2)

    print(f"  Parameters:     {len(flat_original):,}")
    print(f"  FP32 size:      {raw_mb_fp32:.1f} MB")
    print(f"  Int8 size:      {q_mb:.1f} MB  ({100*q_mb/raw_mb_fp32:.0f}% of FP32)")
    print(f"  Base64 total:   {total_b64:.1f} MB")
    print(f"  Scale blocks:   {len(scales):,}")

    metadata.update({
        "dtype": "int8",
        "n_params": int(len(flat_original)),
        "raw_mb_fp32": round(raw_mb_fp32, 2),
        "q_mb": round(q_mb, 2),
        "total_b64_mb": round(total_b64, 2),
        "block_size": 128,
        "snr_db": round(snr, 1),
        "quantized": True,
    })

    layout_json = json.dumps(param_layout, indent=None, separators=(',', ':'))
    meta_json   = json.dumps(metadata, indent=2)

    js = f"""// PortraitGAN Generator Weights — Int8 Quantized
// Auto-generated by export/export_weights.py
// DO NOT EDIT MANUALLY
//
// Parameters: {len(flat_original):,}
// FP32 size:  {raw_mb_fp32:.1f} MB
// Int8 size:  {q_mb:.1f} MB  ({100*q_mb/raw_mb_fp32:.0f}% of FP32)
// SNR:        {snr:.1f} dB
// Block size: 128

const MODEL_METADATA = {meta_json};

const PARAM_LAYOUT = {layout_json};

// Int8 quantized weights (symmetric per-block, block_size=128)
// Dequantize: float_val = int8_val * (scale / 127.0)
const WEIGHTS_INT8_B64 = "{q_b64}";

// Per-block float32 scales (one per 128 weights)
const SCALES_B64 = "{scale_b64}";
"""
    with open(output_path, "w") as f:
        f.write(js)
    print(f"  Written → {output_path}")


# ─────────────────────────────────────────────────────────────────────────────
# METADATA BUILDER
# ─────────────────────────────────────────────────────────────────────────────

def build_metadata(G: Generator, config: dict = None) -> dict:
    from src.model import count_params, model_size_mb
    return {
        "model": "PortraitGAN",
        "version": "1.0",
        "img_size": IMG_SIZE,
        "nz": NZ,
        "num_dims": NUM_DIMS,
        "dim_sizes": list(DIM_SIZES.values()),
        "embed_dim_per_dim": EMBED_DIM_PER_DIM,
        "condition_dim": CONDITION_DIM,
        "n_params": count_params(G),
        "training_config": config or {},
    }


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description="Export PortraitGAN weights to JS")
    p.add_argument("--checkpoint", required=True,
                   help="Path to .pth checkpoint file")
    p.add_argument("--output", default="inference/weights_b64.js",
                   help="Output JS file path")
    p.add_argument("--quantize", choices=["none", "int8"], default="none",
                   help="Quantization: none (float32) or int8")
    p.add_argument("--no_ema", action="store_true",
                   help="Use raw generator weights instead of EMA")
    p.add_argument("--block_size", type=int, default=128,
                   help="Block size for int8 quantization (default: 128)")
    args = p.parse_args()

    print(f"\nPortraitGAN Weight Exporter")
    print(f"Checkpoint: {args.checkpoint}")
    print(f"Output:     {args.output}")
    print(f"Quantize:   {args.quantize}\n")

    # Load weights
    G, state_dict = extract_generator_weights(
        args.checkpoint, use_ema=not args.no_ema
    )
    flat, layout = export_float32(state_dict)
    meta = build_metadata(G)

    # Ensure output dir exists
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)

    if args.quantize == "int8":
        print("\nQuantizing to int8...")
        quantized, scales = quantize_int8(flat, block_size=args.block_size)
        meta["block_size"] = args.block_size
        write_js_int8(flat, quantized, scales, layout, args.output, meta)
    else:
        write_js_float32(flat, layout, args.output, meta)

    print(f"\n✓ Export complete.")
    print(f"  Next step: python export/build_html.py --weights {args.output} --output docs/portrait_gan.html")


if __name__ == "__main__":
    main()
