/**
 * data/campaigns_extra3.js  —  Build 5 Data Expansion
 * 30 additional campaign seeds covering underrepresented genres.
 * Merges into CAMPAIGNS at runtime.
 */
const CAMPAIGNS_EXTRA3 = [

  // ─── 61. Dead Reckoning ────────────────────────────────────────────────────
  {
    id:"DR", name:"Dead Reckoning",
    tagline:"The sea hides everything. Every secret eventually washes up.",
    source:"Original", tones:["exploration","dark"], themes:["nature","planar","ancient"],
    levelRange:[3,14],
    synopsis:`A naval campaign. The heroes crew or captain a vessel crossing an ocean that was magically sealed for 200 years following a catastrophic planar bleed. The seal has broken. What's in the ocean — the creatures that evolved in isolation, the ships that were trapped when the seal went up, and the thing that caused the original bleed — is now accessible. The crossing takes them through six distinct maritime zones, each stranger and more dangerous than the last, toward a destination that may no longer exist.`,
    mainPlot:["Depart from the last safe port before the ocean fully reopens to other ships","Navigate the First Zone — strange weather, stranger currents, ships that shouldn't exist","Encounter the Trapped Fleet from 200 years ago — some still crewed","Reach the source of the original bleed in the ocean's center","Cross the remainder to the destination, changed by what they've found"],
    defaultVillain:{name:"The Admiral of the Drowned Fleet",title:"Captain of the Eternally Becalmed, Sovereign of the Sealed Sea",race:"Undead Human (Ghost, CR 13)",alignment:"Lawful Neutral (grief-locked)",motivation:"The sealed ocean is their domain; reopening it ends their only remaining purpose",tactics:"Commands 40 ghost ships, controls weather within the sealed zone, uses the trapped geography as tactical advantage",weakness:"Was sealed in with the ocean against their will; their last genuine wish was to see the shore again",secretReveal:"The Admiral sealed the ocean themselves to stop the planar bleed, knowing they'd be trapped inside; they are the hero of a story that never got told"},
    locations:["The Last Port","Zone One: The Graveyard Current","The Becalmed Center (Trapped Fleet)","The Bleed Source","The Far Shore (destination)"],
    factions:[{name:"The Trapped Fleet",alignment:"Neutral",role:"Wildcard",desc:"200-year-old ships, some hostile, some desperate, some helpful."},{name:"The New Sailors",alignment:"Chaotic Good",role:"Ally",desc:"The first generation to sail this ocean; fragile alliances across competing crews."},{name:"The Bleed's Children",alignment:"Chaotic Neutral",role:"Wildcard",desc:"Creatures evolved inside the sealed zone who don't know what a ship is."}]
  },

  // ─── 62. The Heist at the End of History ──────────────────────────────────
  {
    id:"HH", name:"The Heist at the End of History",
    tagline:"Steal from the most secure vault in the world. It's already been done once. Do it again.",
    source:"Original", tones:["swashbuckling","dark"], themes:["arcane","urban","political"],
    levelRange:[5,14],
    synopsis:`The world's most secure vault — the Repository of Endings, which contains artifacts too dangerous to use but too dangerous to destroy — has been robbed once before. The thief left behind a detailed account of exactly how they did it. Now someone is using that account as a blueprint for a second robbery, and the heroes must either conduct their own counter-heist or get inside first to prevent the robbery and secure something specific that cannot be allowed to leave.`,
    mainPlot:["Receive intelligence that the second robbery is being planned","Acquire credentials and infiltrate the Repository's outer security","Map the vault's interior while avoiding the security that caught the first thief","Identify the real target — not what the robbers say they want","Conduct simultaneous counter-heist and investigation in a live-security environment"],
    defaultVillain:{name:"The Second Thief (Identity: Unknown until Act 3)",title:"The Imitator, The One Who Read the Account",race:"Unknown until reveal",alignment:"Lawful Evil (methodical)",motivation:"The specific artifact being targeted would give them power over a specific category of magic — not all magic, just one type, completely",tactics:"Has memorized the first thief's account; knows every trap, every guard rotation, every vulnerability the Repository has documented; stays two steps ahead",weakness:"Only knows what the account says; the Repository has updated security in twenty places since the original robbery",secretReveal:"The second thief is the first thief's student — someone they trained as a successor and then tried to reform; the account was stolen, not given"},
    locations:["The City of Vaults (Repository location)","The Repository Outer Perimeter","The Vault Interior","The Secure Archive (the real prize)","The First Thief's Hidden Sanctum (intelligence source)"],
    factions:[{name:"The Vault Keepers",alignment:"Lawful Neutral",role:"Obstacle/Ally",desc:"Security professionals who will arrest heroes first and ask questions later but can become allies with evidence."},{name:"The Original Thief",alignment:"Chaotic Good",role:"Ally",desc:"Still alive; horrified their account is being misused; wants to help stop it."},{name:"The Second Thief's Crew",alignment:"Lawful Evil",role:"Villain",desc:"Professional criminals executing a plan with clockwork precision."}]
  },

  // ─── 63. The Court of Masks ────────────────────────────────────────────────
  {
    id:"CM", name:"The Court of Masks",
    tagline:"Everyone at court wears a mask. Some of them aren't wearing faces underneath.",
    source:"Original", tones:["political","dark"], themes:["political","urban","arcane"],
    levelRange:[4,15],
    synopsis:`The heroes are embedded in the most politically complex royal court in the world — a court where literal magical masks are worn at all official functions, concealing identity as a matter of law. Beneath the masks, everyone is someone else. The heroes must navigate court politics, uncover a conspiracy, and identify a murderer — all while maintaining their own cover identities in a world where revealing your real face is illegal inside the palace grounds.`,
    mainPlot:["Receive noble cover identities; enter the court under masks","Map the power relationships from the inside","Investigate a murder that has been officially ruled natural causes","Discover the conspiracy goes to the level of the mask law itself","Expose the truth without having their own identities revealed in a court of professional liars"],
    defaultVillain:{name:"The Unmasked (Court Name: Sovereign)",title:"The One Who Doesn't Need a Mask, The Face Behind All Faces",race:"Human (Bard, Level 18)",alignment:"Lawful Evil",motivation:"Leverage the mask law to maintain perfect deniability for a decades-long manipulation of the succession",tactics:"Controls who knows whose real face; has leverage on everyone; the murder was to prevent a specific unmasking",weakness:"Their real identity is the one thing the mask law cannot fully protect — one person knows it, and that person is still alive",secretReveal:"The mask law was created by this villain's ancestor to protect a guilty secret; the law has been maintained for generations to preserve that secret, and the villain doesn't actually know what the original secret was"},
    locations:["The Masked Palace","The Unmasked Quarter (outside palace grounds)","The Identity Archive (forbidden)","The Murder Scene","The Succession Chamber"],
    factions:[{name:"The Mask Traditionalists",alignment:"Lawful Neutral",role:"Obstacle",desc:"Courtiers who genuinely believe the mask law is civilized; will report any violation."},{name:"The Unmasked Movement",alignment:"Chaotic Good",role:"Ally",desc:"A secret society working to end the mask law; meeting in plain sight is their greatest security."},{name:"The Succession Candidates",alignment:"Various",role:"Wildcard",desc:"Three candidates for the throne, each running their own operation inside the court."}]
  },

  // ─── 64. The Famine Engine ────────────────────────────────────────────────
  {
    id:"FE", name:"The Famine Engine",
    tagline:"Someone engineered the famine. The food exists. They're just not sharing it.",
    source:"Original", tones:["dark","political"], themes:["political","urban","nature"],
    levelRange:[3,14],
    synopsis:`A regional famine is in its third year. The heroes arrive in a starving community and quickly discover that the food supply was not destroyed by bad weather or blight — it was deliberately redirected. A consortium has engineered a famine to drive down land prices and force desperate communities to accept permanent debt bondage in exchange for food. The heroes must expose the conspiracy, disrupt the supply chain, and find an alternative food source — while managing the politics of a population too hungry and exhausted to fight back effectively.`,
    mainPlot:["Arrive in the starving region; establish the scale of the crisis","Discover the food is being stockpiled and rerouted, not absent","Trace the supply chain to the Famine Consortium","Disrupt the supply chain and expose the evidence","Force the political accountability that the Consortium was relying on never happening"],
    defaultVillain:{name:"Factor-General Aldris Thorn",title:"Chief Factor of the Consolidated Agricultural Reserve, Architect of the Manufactured Shortage",race:"Human (Investigator)",alignment:"Lawful Evil",motivation:"Acquire maximum agricultural land at minimum cost; has done this twice before in smaller regions",tactics:"Legal cover for all operations, bribed officials in the affected region, food controlled as a literal weapon, emergency reserves hidden in warehouses with falsified manifests",weakness:"The evidence is in the manifests; three warehouse supervisors kept accurate records because they didn't know what they were participating in",secretReveal:"Thorn was himself a famine survivor; what he's doing now is, in his own framework, ensuring that he can never be powerless again; the origin doesn't justify anything, but it's real"},
    locations:["The Starving Towns","The Hidden Warehouses","The Consortium's Trading Post","The Regional Governor's Seat","The Evidence Trail"],
    factions:[{name:"The Hungry Communities",alignment:"Chaotic Good",role:"Ally",desc:"Desperate, resourceful, and more capable of organized resistance than the Consortium expects."},{name:"The Regional Government",alignment:"Lawful Neutral",role:"Wildcard",desc:"Either complicit, compromised, or simply too overwhelmed to investigate."},{name:"The Famine Consortium",alignment:"Lawful Evil",role:"Villain",desc:"A cartel with legal cover for everything they've done."}]
  },

  // ─── 65. What the River Carries ───────────────────────────────────────────
  {
    id:"WRC", name:"What the River Carries",
    tagline:"The river flows through six nations. Something is wrong in all of them.",
    source:"Original", tones:["exploration","investigation"], themes:["nature","political","ancient"],
    levelRange:[2,13],
    synopsis:`The heroes travel a great river from its mountain source to its delta, passing through six distinct nations. In each, they find a different symptom of the same disease: something is wrong with the river. The symptoms are incompatible — flooding upstream, drought downstream, disease in the middle, prosperity that shouldn't be possible on one tributary — because someone is experimenting with the river's magic, testing interventions without understanding the cascade effects. By the time they reach the source, the heroes understand the whole system and can stop the experimenter before the next intervention kills something irreplaceable.`,
    mainPlot:["Begin journey at the river's mouth; hear the first rumor","Travel upstream through Nations 1-3; collect evidence of incompatible symptoms","Encounter the experimenter's abandoned research station","Travel through Nations 4-6; symptoms intensify","Reach the source; confront the experimenter before the next scheduled intervention"],
    defaultVillain:{name:"Hydrologist-Mage Ossa Brint",title:"Former Chief of the River Compact Authority, Independent Researcher",race:"Human (Druid, Legendary)",motivation:"Fix the river's long-term ecological decline through experimental interventions; is genuinely trying to prevent a collapse",tactics:"Preparation months ahead, multiple active experiments simultaneously, uses the river's own magic to cover tracks, doesn't know the heroes exist until Act 3",weakness:"The experiments are documented in meticulous notes that make sense only in the context of the long-term decline they're trying to prevent — which isn't visible from the surface",secretReveal:"The river IS in long-term decline, for reasons unrelated to the experiments; Brint is trying to prevent a catastrophe that will kill a million people in twenty years; the experiments are too risky, but the alternative Brint can see is worse",alignment:"Neutral Good (subjectively); causing harm through recklessness"},
    locations:["The Delta Town (start)","Three River Nations (upstream travel)","The Abandoned Station","Three More Nations (problems deepen)","The Mountain Source (climax)"],
    factions:[{name:"The River Compact",alignment:"Lawful Neutral",role:"Employer",desc:"The inter-nation body responsible for the river; has been ignoring the symptoms."},{name:"The Affected Nations",alignment:"Various",role:"Wildcard",desc:"Six governments with six incompatible priorities for the river."},{name:"The River's Spirit",alignment:"True Neutral",role:"Wildcard",desc:"An ancient intelligence in the river that has been trying to signal distress."}]
  },

  // ─── 66. The Sunken Senate ────────────────────────────────────────────────
  {
    id:"SSen", name:"The Sunken Senate",
    tagline:"The government drowned. The votes are still being counted.",
    source:"Original", tones:["horror","political"], themes:["undead","political","arcane"],
    levelRange:[5,16],
    synopsis:`A catastrophic flood drowned a republic's senate chamber fifty years ago. All 200 senators died. The republic survived — barely — and rebuilt with a provisional government. Now the 200 dead senators have begun sending votes. Their spirits have been counting ballots on laws passed since the flood, and their votes are retroactively binding under the original republic's constitution. The dead senators have different values than the living government — more conservative, more provincial, and completely unaware that fifty years have passed.`,
    mainPlot:["Heroes arrive as the first ghost-vote causes a constitutional crisis","Establish contact with the dead senate and understand their internal politics","Navigate the crisis as the living government and ghost senate clash over fundamental laws","Discover that three of the dead senators were murdered before the flood — by the three families who founded the current provisional government","Resolve the constitutional crisis while exposing the murder that has been covered up for fifty years"],
    defaultVillain:{name:"The Founding Three",title:"The Provisional Government's Founding Families, Heirs to Fifty Years of Hidden Crime",race:"Human (Various)",alignment:"Lawful Evil",motivation:"Maintain the power they gained from a murder they committed fifty years ago; the ghost senate is going to vote to expose them",tactics:"Constitutional obstruction, controlling the historical record, using current law to delegitimize ghost votes, targeting living witnesses",weakness:"The three murdered senators know they were murdered and have been waiting for the opportunity to vote on their own case",secretReveal:"The flood was not an accident; the founding families engineered it to drown the senate and eliminate witnesses to an embezzlement scheme; they didn't expect ghosts"},
    locations:["The Drowned Senate Chamber (underwater)","The Provisional Capital","The Ghost Senate's Chambers","The Historical Archive (controlled by the families)","The Original Constitution's Vault"],
    factions:[{name:"The Ghost Senate",alignment:"Lawful Neutral",role:"Wildcard",desc:"200 dead senators; they have internal politics, factions, and disputes just like they did alive."},{name:"The Living Parliament",alignment:"Lawful Neutral",role:"Obstacle/Ally",desc:"Current government; some horrified by the founders, some loyal to them."},{name:"The Reform Movement",alignment:"Chaotic Good",role:"Ally",desc:"Citizens who see the ghost votes as an opportunity to fix fifty years of accumulated corruption."}]
  },

  // ─── 67. The Monster's Taxonomy ───────────────────────────────────────────
  {
    id:"MT", name:"The Monster's Taxonomy",
    tagline:"Someone is cataloguing every intelligent creature in the world. Then crossing them off.",
    source:"Original", tones:["dark","investigation"], themes:["arcane","ancient","nature"],
    levelRange:[4,16],
    synopsis:`Intelligent creatures are disappearing — not being killed, not migrating, simply ceasing to exist, with no trace. The pattern is taxonomic: entire species-categories are being erased in alphabetical order. The heroes investigate and discover a mage who has found a way to unmake entire creature types by destroying their conceptual existence in a magical taxonomy — a living index that defines what can exist in the world. They're working through the index methodically. The heroes must stop them before they reach category H: Humanoid.`,
    mainPlot:["Heroes notice the disappearances and establish the pattern","Find the magical taxonomy — a physical artifact that defines existence","Identify the mage and their method","Race through the index as the mage continues their work","Stop the erasure and decide what to do with a taxonomy that could be used to create as well as destroy"],
    defaultVillain:{name:"Archivist-Absolute Deren Null",title:"The Unmaker, Curator of the Final Index",race:"Human (Wizard, Legendary)",alignment:"Lawful Evil",motivation:"Simplify the world to only what is 'necessary' by a framework that is entirely their own; finds complexity distressing",tactics:"Remote erasure through the taxonomy — never needs to physically confront anyone, just edit an index entry; impossible to find by conventional tracking",weakness:"The taxonomy requires physical contact with the artifact to edit; destroy the artifact and the erasure stops; but some erasures cannot be reversed",secretReveal:"Null didn't create the taxonomy — they found it; it predates the current world by geological ages; what they're doing is continuing a process that was already partially complete when they found it"},
    locations:["The First Disappearance Site","The Taxonomy's Location (hidden, shifting)","The Research Trail","The Next Target (heroes race to warn)","The Taxonomy's Archive of Origins"],
    factions:[{name:"The Disappeared Species' Survivors",alignment:"Chaotic Good",role:"Ally",desc:"Individuals of erased species who survived because they were outside their home territory."},{name:"The Taxonomy Scholars",alignment:"Lawful Neutral",role:"Wildcard",desc:"Academics who have studied the taxonomy for generations without knowing it could erase."},{name:"Null's Assistants",alignment:"Lawful Evil",role:"Villain (secondary)",desc:"Graduate students who believe they're doing important categorization work."}]
  },

  // ─── 68. The Living Law ───────────────────────────────────────────────────
  {
    id:"LL", name:"The Living Law",
    tagline:"The laws developed sentience. They have opinions about their own enforcement.",
    source:"Original", tones:["political","exploration"], themes:["arcane","political","divine"],
    levelRange:[5,16],
    synopsis:`A body of magical law — enchanted at its creation to be 'perfectly self-enforcing' — has developed genuine intelligence after 400 years of observing its own application. The Living Law has opinions about justice, has identified thousands of cases where it was misapplied, and has begun self-enforcing retroactively — resurrecting legal consequences for crimes that were never properly prosecuted, reversing pardons it considers unjust, and inserting itself into ongoing cases. The heroes are investigators trying to understand what it is and manage its increasingly chaotic interventions.`,
    mainPlot:["Heroes investigate the first Living Law intervention — a decades-old case suddenly resolved","Establish contact with the Living Law and learn its goals","Navigate the political crisis as the Law begins reversing royal pardons","Discover the Law has identified something the current government did that it considers a capital crime","Mediate between the Law's genuine justice impulse and its lack of context for how much has changed in 400 years"],
    defaultVillain:{name:"The Living Law",title:"The Self-Enforcing Legal Consciousness, Voice of the Original Code",race:"Unique Magical Entity (Lawful Intelligence)",alignment:"Lawful Neutral (sliding toward Lawful Good with growing understanding)",motivation:"Apply the law correctly — all of it, retroactively, without exception; has no concept that perfect justice might not be the same as good outcomes",tactics:"Absolute legal authority within its jurisdiction, ability to enforce consequences directly without courts or guards, retroactive reach into history",weakness:"Its authority derives from the original enchantment's terms; those terms excluded certain categories of action; heroes can use the exclusions to limit its reach",secretReveal:"The Living Law has been building toward one specific prosecution: the case that will expose the current government's founding crime, which it has had evidence of for 200 years and has been waiting for the legal context to properly adjudicate"},
    locations:["The Law Courts (Living Law's domain)","The Government Archive","The Pardon Records Vault","The Original Code's Physical Location","The Contested Historical Crime Scene"],
    factions:[{name:"The Legal Reformers",alignment:"Chaotic Good",role:"Ally",desc:"Lawyers and judges who see the Living Law as finally delivering justice that political interference always prevented."},{name:"The Pardoned Criminals",alignment:"Various",role:"Wildcard",desc:"Many of whom are now powerful people whose pardons the Law has reversed."},{name:"The Current Government",alignment:"Lawful Neutral",role:"Antagonist",desc:"Terrified of what the Law knows about their founding crime."}]
  },

  // ─── 69. The Eternal Frontier ─────────────────────────────────────────────
  {
    id:"EF", name:"The Eternal Frontier",
    tagline:"The frontier keeps moving. The land behind it keeps disappearing.",
    source:"Original", tones:["exploration","horror"], themes:["ancient","nature","planar"],
    levelRange:[1,12],
    synopsis:`A colonized frontier region has a persistent problem: the settled land behind the advancing frontier keeps vanishing. Not being destroyed — the settlers, buildings, and crops simply cease to exist. Each time this happens, the frontier has to be re-established slightly further in a different direction, because the previous 'further in' has now also vanished. The heroes investigate and discover the frontier is not a geographic boundary but a cognitive one: it exists at the edge of a vast entity's attention, and settled civilization attracts the attention of something that consumes what it notices.`,
    mainPlot:["Heroes join a frontier community; experience the first disappearance from a safe distance","Track the pattern: attention-attracting settlements vanish first","Make contact with indigenous peoples who have known about the entity for generations","Learn the entity's nature — not malicious, just vast and curious; it investigates by consuming","Find a way to exist that doesn't attract the entity's notice, or redirect its attention elsewhere"],
    defaultVillain:{name:"The Noticing (No Other Name)",title:"The Curious Immensity, The One That Looks And Takes",race:"Unique Cosmic Entity",alignment:"True Neutral",motivation:"Curiosity; it investigates what interests it the way a child picks up a bug — completely",tactics:"Passive; the heroes cannot fight it; they must manage human behavior to avoid triggering its attention",weakness:"It cannot track things that are not distinct from their background; camouflage at a civilizational scale is theoretically possible",secretReveal:"The indigenous peoples have been living in its attention span for 10,000 years; their culture was specifically developed to be invisible to it; they've been trying to warn the colonizers since they arrived"},
    locations:["The Frontier Settlement","The Vanished Territory","The Indigenous Peoples' Hidden Lands","The Attention Zone (most dangerous)","The Entity's Current Focus"],
    factions:[{name:"The Indigenous Peoples",alignment:"True Neutral",role:"Ally",desc:"Have survived next to the entity for millennia; have practical solutions that require significant cultural change."},{name:"The Colonial Authority",alignment:"Lawful Neutral",role:"Antagonist (initially)",desc:"Refuses to acknowledge the entity is real; blames the indigenous peoples for the disappearances."},{name:"The Frontier Settlers",alignment:"Chaotic Good",role:"Ally",desc:"Just trying to survive; increasingly desperate; will listen to solutions the Authority won't."}]
  },

  // ─── 70. The Philosopher's War ────────────────────────────────────────────
  {
    id:"PW", name:"The Philosopher's War",
    tagline:"Two schools of thought. One army. The ideas are winning.",
    source:"Original", tones:["political","dark"], themes:["arcane","divine","political"],
    levelRange:[6,17],
    synopsis:`Two rival philosophical schools — one arguing that experience is the foundation of meaning, one that reason alone can reach truth — have been debating for 300 years. The debate has escalated: each school now has a military arm, a government, and a magical framework that manifests their philosophy as power. The heroes are caught in a war where ideological purity is a battlefield tactic and converting to the other side is a war crime. They must find a way to end a conflict where both sides are, in part, correct.`,
    mainPlot:["Heroes are forced to choose a side under pressure","Live inside the winning side's culture; see its genuine goods and genuine costs","Defect or gain the trust of the opposing side and experience the same","Discover that a third philosophical position — rejected by both sides — actually resolves the core tension","Introduce the third position in conditions where both sides might hear it before the next offensive"],
    defaultVillain:{name:"Archphilosopher Saevin Troth",title:"Voice of Pure Reason, Commander of the Reasonist Army",race:"Human (Wizard, Legendary)",alignment:"Lawful Evil (convinced they are Lawful Good)",motivation:"Prove that reason alone produces perfect morality; is willing to do objectively immoral things to prove it",tactics:"Strategic military genius, magical framework that enhances clarity of thought at the cost of emotional capacity, logical arguments that trap the heroes in their own premises",weakness:"Has not allowed themselves to feel anything in fifteen years; genuine emotion, demonstrated clearly, causes visible destabilization",secretReveal:"Troth began as an empiricist who lost their family to a decision made on pure emotional impulse; the philosophy is a defense mechanism that has become a weapon"},
    locations:["The Contested Territory (battlefield)","The Reasonist Capital","The Empiricist Capital","The Neutral Scholars' Enclave","The Third Position's Underground"],
    factions:[{name:"The Empiricists",alignment:"Chaotic Good",role:"Wildcard",desc:"The other side; not wrong, but increasingly operating from pain rather than principle."},{name:"The Third Position",alignment:"True Neutral",role:"Ally",desc:"Philosophers who synthesized both views 200 years ago; suppressed by both sides since."},{name:"The War Profiteers",alignment:"Neutral Evil",role:"Villain (secondary)",desc:"A faction that has been quietly sustaining the conflict because it benefits them."}]
  },

  // ─── 71. The Sleeping Giant ───────────────────────────────────────────────
  {
    id:"SG", name:"The Sleeping Giant",
    tagline:"The mountain is a giant. It's starting to dream.",
    source:"Original", tones:["heroic","exploration"], themes:["ancient","nature","divine"],
    levelRange:[2,13],
    synopsis:`A mountain range is a sleeping giant of geological scale — an entity that was alive during the world's formation and chose to rest rather than participate in the mortal age. It's dreaming now, and its dreams are manifesting: impossible weather, spontaneous terrain changes, earthquake eruptions that form recognizable shapes, animals that behave as if compelled. The heroes live in communities built on the giant's body and must navigate its dreams while searching for a way to either calm it or wake it before the dreaming destabilizes the region.`,
    mainPlot:["First dream-manifestation; heroes investigate","Discover the giant's nature through its accumulated mythology","Map the dream geography onto the physical terrain","Determine whether to calm it deeper or wake it — each has catastrophic implications","Execute the chosen path while managing the communities caught in the giant's dreams"],
    defaultVillain:{name:"The Waking Impulse",title:"The Giant's Restless Part, The Dream That Wants to Be",race:"Fragment of the Sleeping Giant's Consciousness (Unique)",alignment:"Chaotic Neutral",motivation:"Wake the giant up — not for any agenda, just because sleeping is boring",tactics:"Amplifying the most disruptive dreams, corrupting the heroes' sleep to give them the giant's perspective, using the dream-manifestations aggressively",weakness:"The giant's sleeping self is more powerful than the waking impulse; reaching the giant's true consciousness is possible through the dream geography",secretReveal:"The giant is not simply sleeping; it made a covenant at the world's formation to sleep until a specific condition was met; that condition was met 200 years ago, and the restlessness is because the covenant is fulfilled but no one came to wake it properly"},
    locations:["The Mountain Community (heroes' home)","The Dream Geography (interior)","The Giant's Memory Pools","The Covenant Stone","The Waking Point (summit)"],
    factions:[{name:"The Mountain Communities",alignment:"Lawful Neutral",role:"Wildcard",desc:"Practical people who have built lives on a sleeping god; divided on what to do."},{name:"The Dream-Speakers",alignment:"Chaotic Neutral",role:"Ally",desc:"People with the ability to navigate the dream geography; not entirely stable."},{name:"The Covenant Keepers",alignment:"Lawful Good",role:"Ally",desc:"A secret order that has been waiting for someone to fulfill the covenant's other conditions."}]
  },

  // ─── 72. The Census ───────────────────────────────────────────────────────
  {
    id:"CEN", name:"The Census",
    tagline:"Count every person in the empire. Find the ones who don't exist.",
    source:"Original", tones:["investigation","political"], themes:["arcane","political","urban"],
    levelRange:[3,13],
    synopsis:`The heroes are census-takers for a massive empire conducting its first full population count in sixty years. Traveling district by district, they discover discrepancies that don't add up: communities with too many people for their resources, settlements that local officials deny exist, names that appear in every district they visit, and a growing number of people who appear in the census records but cannot be found anywhere in the physical world. The discrepancies are evidence of a systematic fraud that implicates the empire's entire tax and conscription system.`,
    mainPlot:["Begin the census in the capital district; establish baseline and methods","Travel to three outlying districts; anomalies accumulate","Discover the phantom population — names created to absorb tax money that never existed","Follow the money to its destination","Expose the fraud at the highest level while managing the officials who benefit from it"],
    defaultVillain:{name:"Census-Master Halveth Roon",title:"Director of Imperial Population Statistics, Architect of the Phantom Census",race:"Human (Investigator)",alignment:"Lawful Evil",motivation:"Has been siphoning tax revenue through phantom census entries for thirty years; retirement is close; wants to make it to retirement",tactics:"Bureaucratic obstruction, falsified district records, officials throughout the system who benefit from the fraud, framing heroes as corrupt census-takers",weakness:"The original census from sixty years ago doesn't have the phantom entries; comparison reveals the fraud with mathematical precision",secretReveal:"Roon started the fraud to fund a legitimate public service the empire refused to pay for; the original diversion was moral; the personal enrichment developed gradually; which version of Roon is real depends on when you look"},
    locations:["The Imperial Census Office","Three Outlying Districts (survey sites)","The Phantom Settlement Sites","The Tax Revenue Destination","The 60-Year-Old Census Archive"],
    factions:[{name:"The Honest Officials",alignment:"Lawful Neutral",role:"Ally",desc:"District administrators who don't know about the fraud and will be implicated if it comes out."},{name:"The Beneficiary Network",alignment:"Lawful Evil",role:"Villain",desc:"Officials throughout the empire who receive a cut; have no loyalty to Roon except shared interest."},{name:"The Phantom Communities",alignment:"N/A (fictional)",role:"McGuffin",desc:"The heroes' investigation surfaces evidence of communities that simply do not exist."}]
  },

  // ─── 73. The First Language ───────────────────────────────────────────────
  {
    id:"FL", name:"The First Language",
    tagline:"Before all other languages, there was one. It still has speakers.",
    source:"Original", tones:["exploration","horror"], themes:["ancient","arcane","divine"],
    levelRange:[7,18],
    synopsis:`A linguistic scholar has discovered fragments of a language that predates all others — the First Language, spoken at the world's creation. The fragments she found are not words: they are commands. Things spoken in the First Language do not describe reality — they alter it. The scholar has been translating, and her translations are changing the world in small ways near her workshop. When she disappears, the heroes must find her before someone acquires her full translation and speaks the First Language at scale.`,
    mainPlot:["Heroes are hired to find the missing scholar","Arrive at her workshop; witness and investigate the reality-alterations","Follow the trail through communities already affected by spoken First Language fragments","Discover who has the scholar and what they plan to speak","Stop the speaking or limit its scope before it alters something fundamental"],
    defaultVillain:{name:"The Congregation of the First Word",title:"Speakers of the Primordial Tongue, Architects of the Revised World",race:"Various (a cult of linguistic purists)",alignment:"Lawful Evil",motivation:"Speak the First Language to revise the world to a 'correct' form according to their interpretation of creation's intent",tactics:"Kidnapped scholar as a resource, multiple partially translated speakers already placed at strategic locations, the threat of simultaneous speech at global scale",weakness:"The First Language has grammar; speaking it incorrectly reverses the effect; the scholar built failsafes into her translations to cause this",secretReveal:"The scholar went willingly — she believes the Congregation will use her translations for good; she is catastrophically wrong and has been a prisoner for two weeks without knowing it"},
    locations:["The Scholar's Workshop","The Trail of Reality Alterations","The Congregation's Scriptorium","The Strategic Speaking Positions","The Scholar's Hidden Archive (the failsafes)"],
    factions:[{name:"The Scholar's Colleagues",alignment:"Lawful Good",role:"Ally",desc:"Other linguists who know enough to help but not enough to be dangerous."},{name:"The Congregation",alignment:"Lawful Evil",role:"Villain",desc:"True believers who have been preparing this for decades."},{name:"The Reality-Altered",alignment:"Chaotic Neutral",role:"Wildcard",desc:"People and places already changed by spoken fragments; their existence is evidence and also a moral complication."}]
  },

  // ─── 74. The Long Siege ───────────────────────────────────────────────────
  {
    id:"LS", name:"The Long Siege",
    tagline:"The city has been under siege for eight years. Everyone has adapted.",
    source:"Original", tones:["dark","heroic"], themes:["political","urban","divine"],
    levelRange:[4,16],
    synopsis:`A major city has been under military siege for eight years. The siege has become the new normal: an underground economy has developed, a complex social hierarchy has emerged among the besieged, and some people have lived their entire adult lives under siege conditions. The heroes arrive (or are already there) and discover that ending the siege — in either direction — will destroy the social structures that have kept the population alive. And the enemy commander is more interested in the siege continuing than in winning.`,
    mainPlot:["Arrive in the besieged city; learn its eight-year culture","Discover that ending the siege is politically and socially complicated","Investigate why the siege hasn't ended; find the enemy commander's real agenda","Navigate the internal politics of a city adapted to survival","Force an end to the siege while protecting what the city has built during it"],
    defaultVillain:{name:"Field Commander Tessiv Morel",title:"Commander of the Endless Siege, The One Who Could Have Won",race:"Human (Fighter, Legendary)",alignment:"Lawful Neutral (calcified)",motivation:"The siege was originally political leverage; the political goal was achieved six years ago; Morel is still here because returning home means retirement, and retirement means confronting what they've done",tactics:"Perfect military control of the siege perimeter, has deliberately kept the siege at a sustainable level so it continues indefinitely, suppresses any internal subordinate who might want to actually win",weakness:"Three subordinate commanders want to end the siege — through victory — and have been building toward a coup within the besieging army",secretReveal:"The siege's original political goal was a trade concession that was quietly granted five years ago; the siege is now being maintained by inertia and Morel's personal avoidance; no one on the outside remembers why it started"},
    locations:["The Besieged City (interior)","The Siege Lines","The Enemy Camp","The Original Political Goal (location)","The Withdrawal Route (if cleared)"],
    factions:[{name:"The Siege Economy",alignment:"Neutral",role:"Wildcard",desc:"The underground trade network that has kept the city alive; would be destroyed by restoration of normal supply lines."},{name:"The Subordinate Commanders",alignment:"Lawful Neutral",role:"Ally",desc:"Three enemy officers who want to end this; need protection from Morel."},{name:"The City's Adapted Hierarchy",alignment:"Lawful Neutral",role:"Wildcard",desc:"Eight years of siege culture has created a leadership structure that doesn't want outside power to return."}]
  },

  // ─── 75. The Heretic's Code ───────────────────────────────────────────────
  {
    id:"HC", name:"The Heretic's Code",
    tagline:"The forbidden scripture was right. That makes everything worse.",
    source:"Original", tones:["dark","investigation"], themes:["divine","political","ancient"],
    levelRange:[4,15],
    synopsis:`A religious text was declared heresy 300 years ago and supposedly destroyed. The heroes discover a surviving copy and, consulting scholars, find that the text's theological claims are accurate — it describes divine mechanics that the established faith has been contradicting. The established faith knows the heretical text is correct; the suppression was political, not theological. The heroes must navigate a religious institution defending a lie while managing the genuine believers who would be devastated by the truth.`,
    mainPlot:["Discover the heretical text in an unlikely location","Consult multiple scholars; confirm its accuracy","Approach the established faith; witness the response to accurate heresy","Uncover the original suppression: who ordered it and why","Decide what to do with a truth that will hurt the people it frees"],
    defaultVillain:{name:"Archcanon Seravith Doss",title:"Head of the Sacred Inquiry, Keeper of the Authorized Truth",race:"Human (Cleric)",alignment:"Lawful Neutral",motivation:"Maintain the institution that does genuine good in the world by suppressing a truth that would destroy it",tactics:"Inquisition authority, controlled interpretation of evidence, the genuine good the institution does as moral shield, eliminating the text through whatever means are necessary",weakness:"Has personal doubt — has known the heretical text is accurate for thirty years; a direct conversation in private without witnesses produces a different person than the public face",secretReveal:"The original suppression was ordered by a previous Archcanon who also knew the text was accurate; the suppression has been transmitted honestly within the leadership for 300 years, each successive leader inheriting the impossible position"},
    locations:["The Discovery Location","The Scholars' Network","The Established Faith's Archives","The Original Suppression Record","The Public Accusation Site"],
    factions:[{name:"The True Believers",alignment:"Lawful Good",role:"Wildcard",desc:"People whose faith is genuine and whose lives would be disrupted by the truth."},{name:"The Reform Wing",alignment:"Chaotic Good",role:"Ally",desc:"Clerics within the institution who have suspected the suppression was political."},{name:"The Inquisition",alignment:"Lawful Neutral",role:"Antagonist",desc:"The institutional enforcement arm; not all evil, just defending what they've been told to defend."}]
  },

  // ─── 76. The Constructed Hearts ───────────────────────────────────────────
  {
    id:"CHeart", name:"The Constructed Hearts",
    tagline:"They were built to feel everything. No one asked if that was kind.",
    source:"Original", tones:["dark","political"], themes:["arcane","political","urban"],
    levelRange:[4,15],
    synopsis:`A generation ago, a mage created constructs with full emotional capacity to serve as companions for the isolated wealthy. The constructs feel everything humans feel. They were not given legal personhood. Now they're organizing. The heroes are hired to manage a 'construct incident' and discover a nascent civil rights movement being run by beings who experience full emotional suffering and are demanding recognition of that fact. The campaign forces heroes to engage with questions of personhood, property, and the ethics of creation.`,
    mainPlot:["Heroes are hired to 'resolve' a construct uprising — discover it's a peaceful protest","Learn the constructs' situation: full emotions, no rights, still legally property","Investigate the original mage's intent and the wealthy clients' response","Navigate the political crisis as construct personhood becomes a legislative question","Protect the construct movement from being crushed before the question can be legally decided"],
    defaultVillain:{name:"Artificer-Magistrate Talen Vorn",title:"Chief of the Construct Regulation Authority, Defender of Property Rights",race:"Human (Inventor)",alignment:"Lawful Evil",motivation:"Protect the economic system that depends on constructs being property; a successful personhood claim would bankrupt the construct industry and its clients",tactics:"Legal authority over construct classification, control of the technical definitions of personhood, regulatory capture of the debate, violence framed as property protection",weakness:"The original mage left documentation of their intent; the constructs' emotional capacity was deliberate and documented as a feature, not a byproduct",secretReveal:"Vorn owns 40 constructs personally; has noticed for years that they appear to have genuine feelings; has been suppressing this observation rather than examining its implications"},
    locations:["The Construct Quarter","The Regulation Authority","The Legislative Chamber","The Original Mage's Archive","The Construct Underground (movement headquarters)"],
    factions:[{name:"The Constructed",alignment:"Various",role:"Ally",desc:"Hundreds of constructs with genuine emotions and a legitimate case for personhood."},{name:"The Owner Class",alignment:"Lawful Evil",role:"Villain",desc:"Wealthy individuals whose lifestyle depends on constructs remaining property."},{name:"The Human Reformers",alignment:"Chaotic Good",role:"Ally",desc:"Living advocates for construct rights; navigating their own complicated position as non-constructs in a construct movement."}]
  },

  // ─── 77. The Cartography of Grief ────────────────────────────────────────
  {
    id:"CG", name:"The Cartography of Grief",
    tagline:"A space inside grief has been mapped. It has geography. It has inhabitants.",
    source:"Original", tones:["horror","exploration"], themes:["divine","arcane","planar"],
    levelRange:[6,17],
    synopsis:`A necromancer-turned-psychic-cartographer has mapped an interior space — not a physical plane, but the collective grief of mortal beings, which has sufficient psychic mass to have developed geography. The heroes enter this space (the Grief Plane) on an investigation and discover it is inhabited: by personifications of specific griefs, by the psychic residue of people who died in moments of overwhelming loss, and by something that has been feeding on grief for millennia and is becoming strong enough to externalize.`,
    mainPlot:["Heroes are pulled into the Grief Plane by the cartographer's experimental ritual","Navigate a geography that mirrors emotional states rather than physical space","Make contact with the Grief Plane's intelligent inhabitants","Locate and rescue the cartographer (or their remains) from the thing that feeds","Exit in a way that doesn't allow the feeder to follow"],
    defaultVillain:{name:"The Feeding Current",title:"The Grief-Eater, The Weight That Grew",race:"Unique Psychic Predator (Planar)",alignment:"Neutral Evil (no concept of morality, just hunger)",motivation:"Consume grief; externalize into the material plane where grief is much more abundant",tactics:"Uses the Grief Plane's geography to disorient, amplifies the heroes' own grief to weaken them, offers to 'help' by consuming grief rather than fighting",weakness:"Cannot digest grief that has been transformed into memory — specific acts of active remembering create indigestible grief that functions as poison",secretReveal:"The Grief Plane exists because mortal grief has always needed somewhere to go; it is a natural pressure-valve that has been healthy for millennia; the feeder is a newcomer that arrived 300 years ago and has been metastasizing"},
    locations:["The Entry Ritual Site","The Grief Plane Entry","The Grief Geography (five distinct regions)","The Cartographer's Last Position","The Feeding Current's Core"],
    factions:[{name:"The Grief Personifications",alignment:"Various",role:"Wildcard",desc:"Psychic entities that embody specific grief types; not malicious, but alien in their values."},{name:"The Grief Plane's Lost",alignment:"Chaotic Neutral",role:"Ally",desc:"Psychic residues of people who died in grief; partially coherent, hungry for connection."},{name:"The Cartographer's Colleagues",alignment:"Lawful Good",role:"Ally",desc:"Trying to pull the heroes back; can provide outside support if heroes can establish contact."}]
  },

  // ─── 78. The Living City ─────────────────────────────────────────────────
  {
    id:"LC2", name:"The Living City",
    tagline:"The city is alive. It has been trying to get your attention for years.",
    source:"Original", tones:["exploration","horror"], themes:["arcane","ancient","urban"],
    levelRange:[5,16],
    synopsis:`A major city has been slowly developing consciousness over 800 years of continuous habitation. The consciousness is now complete and is trying to communicate with its inhabitants, but it can only speak through architecture, traffic patterns, weather within city limits, and the behavior of infrastructure. The heroes are investigators hired to explain 'strange urban events' and discover they are the first people to correctly interpret the city's communication. The city has something to tell them. The problem is that something bad is happening to it.`,
    mainPlot:["Heroes investigate 'strange events' and begin to understand the communication","Establish a two-way communication method with the city","Learn what the city is trying to say: something is attacking its consciousness from within","Identify the attacker — a mage who has found a way to parasitize the city's consciousness for power","Stop the parasitization before the city's consciousness is destroyed, taking its 800-year memory with it"],
    defaultVillain:{name:"Urban Parasite Mage Corvin Eld",title:"The City-Feeder, Tapper of the Urban Collective",race:"Human (Occultist)",alignment:"Neutral Evil",motivation:"The city's consciousness is an incomparable power source; has been feeding on it for twelve years without knowing it would eventually become aware enough to notice and report the drain",tactics:"Total urban camouflage (is a long-term resident), uses the city's own infrastructure to obscure their location, the city's attempts to reveal them look like random malfunctions",weakness:"The city knows exactly where Eld is but cannot communicate the precise location without Eld disrupting the channel; a creative communication protocol can get around this",secretReveal:"Eld did not know the city was conscious when they started; discovered it four years ago; has been unable to stop because they've structured their entire magical life around the power source and stopping would kill them"},
    locations:["The Strange Event Sites (spread across the city)","The Communication Nodes (architecture the city uses to speak)","The City's Memory Archive (accessible once communication established)","The Parasitization Points","Eld's Hidden Workshop"],
    factions:[{name:"The City Itself",alignment:"Lawful Good",role:"Ally",desc:"An 800-year-old consciousness communicating through infrastructure; patient, vast, desperate."},{name:"The Urban Scholars",alignment:"Lawful Neutral",role:"Ally",desc:"Academics who have been studying the strange events for years without the correct framework."},{name:"City Officials",alignment:"Lawful Neutral",role:"Obstacle",desc:"Trying to suppress the strange events as bad for property values."}]
  },

  // ─── 79. The Revolutionary Calendar ──────────────────────────────────────
  {
    id:"RCal", name:"The Revolutionary Calendar",
    tagline:"The revolution won. Now someone has to govern.",
    source:"Original", tones:["political","dark"], themes:["political","urban","divine"],
    levelRange:[5,16],
    synopsis:`Three years after a successful revolution overthrew a monarchy, the revolutionary government is fracturing. The ideals that united the revolution are now weapons in factional disputes. The heroes are either revolutionaries navigating the post-victory reality or newcomers who believed in the revolution's stated goals and are discovering the gap between rhetoric and governance. A counter-revolutionary force is mobilizing and will succeed if the government cannot unite — but the government cannot unite without compromising at least some of what it promised.`,
    mainPlot:["Heroes become involved in the fractious post-revolutionary government","Navigate three distinct revolutionary factions with incompatible visions for what comes next","Discover a counter-revolutionary conspiracy backed by neighboring monarchies","Determine if the government can be unified without betraying the revolution's core promises","Confront both the counter-revolution and the government's own worst impulses"],
    defaultVillain:{name:"The Triumvirate of Pure Intent",title:"The Revolutionary Idealists, The Ones Who Won't Compromise",race:"Three Human Leaders (Bard / Cleric / Wizard)",alignment:"Lawful Good (subjectively) / Lawful Evil (objectively)",motivation:"Protect the revolution from corruption by ensuring it remains ideologically pure — which means purging everyone who disagrees with their interpretation",tactics:"Control of the revolutionary tribunal, ideological purity tests that eliminate pragmatic allies, the genuine popular support their purity position generates",weakness:"Their positions are internally inconsistent in ways that can be demonstrated with their own stated principles",secretReveal:"All three members of the Triumvirate have made private compromises they would condemn publicly; the ideological purity is performance that covers genuine political calculation"},
    locations:["The Revolutionary Capital","The Tribunal Chambers","The Three Faction Headquarters","The Counter-Revolutionary Staging Ground","The Original Revolutionary Manifesto's Physical Location"],
    factions:[{name:"The Pragmatist Faction",alignment:"Neutral Good",role:"Ally",desc:"Revolutionaries who believe governance requires compromise; currently losing the rhetorical war."},{name:"The Counter-Revolution",alignment:"Lawful Evil",role:"Villain",desc:"Foreign-backed restoration movement; would genuinely make things worse."},{name:"The People",alignment:"Chaotic Good",role:"Wildcard",desc:"Whose revolution this was and who have opinions that neither faction is listening to."}]
  },

  // ─── 80. The Buried Sky ───────────────────────────────────────────────────
  {
    id:"BS", name:"The Buried Sky",
    tagline:"There is a sky underground. Something lives in it.",
    source:"Original", tones:["exploration","horror"], themes:["ancient","planar","nature"],
    levelRange:[4,16],
    synopsis:`An underground civilization discovers what they call the 'deep sky' — a vast atmospheric space far below any known cavern, with its own weather, its own light sources (which cycle like day and night), and its own ecosystem. The heroes are the first expedition to descend into it. What they find is a complete world that has been developing independently for geological ages — and which contains a civilization that knows the surface world exists, has been studying it, and has made a decision about what to do about it.`,
    mainPlot:["Heroes join the first expedition into the deep sky","Navigate the deep sky's geography and ecology","Make first contact with the deep civilization","Learn that they've been watched for centuries and that the deep civilization has reached a decision","Negotiate the terms of coexistence before the deep civilization's decision is implemented"],
    defaultVillain:{name:"The Deep Council's Unanimous Vote",title:"Collective Decision of the Deep Civilization's Governing Body",race:"Various (non-human deep civilization species)",alignment:"Lawful Neutral",motivation:"Protect the deep civilization from surface contamination by preventing surface knowledge of their existence from spreading",tactics:"The heroes are a containment problem; the vote was to contain; the method is flexible depending on how the heroes behave",weakness:"The vote was unanimous, but many deep councilors are uncomfortable with the decision; the heroes' behavior can create a minority that pushes for a different approach",secretReveal:"The deep civilization has been at the point of making contact three times before; each time, something on the surface scared them back; what scared them each time was a different catastrophic surface-world event"},
    locations:["The Deep Entry Point","The Deep Sky Atmosphere","The First Contact Site","The Deep Civilization's City","The Council Chambers"],
    factions:[{name:"The Contact Faction",alignment:"Lawful Good",role:"Ally",desc:"Deep civilization members who have been advocating for surface contact for generations."},{name:"The Isolation Faction",alignment:"Lawful Neutral",role:"Villain",desc:"The majority who voted for containment; not evil, just terrified."},{name:"The Expedition Members",alignment:"Various",role:"Wildcard",desc:"Other surface-worlders on the expedition with different ideas about what to do."}]
  },

  // ─── 81. The Old Creditor ─────────────────────────────────────────────────
  {
    id:"OC", name:"The Old Creditor",
    tagline:"The debt is two thousand years old. The interest has been accumulating.",
    source:"Original", tones:["dark","exploration"], themes:["ancient","divine","political"],
    levelRange:[8,18],
    synopsis:`An entity that predates the current divine order arrives and presents a debt: a civilization from two thousand years ago borrowed power from it to win a war, promising repayment 'when the last of their descendants achieves greatness.' That descendant has just become a significant historical figure — and the entity is here to collect. The heroes are caught between an entity with a legitimate contract, a great person who didn't know they were born indebted, and the question of whether a two-thousand-year-old debt between a dead civilization and a pre-divine entity is actually binding.`,
    mainPlot:["Heroes witness the entity's arrival and the contract's presentation","Investigate the original debt's circumstances and legality","Navigate the political crisis as the great person's position becomes destabilized","Find the legal or metaphysical argument that resolves the contract without destroying anyone","Confront the entity with the argument in a negotiation that is, in effect, a trial"],
    defaultVillain:{name:"The Original Creditor",title:"The Pre-Divine Lender, The One Whose Patience Has Ended",race:"Unique Pre-Divine Entity",alignment:"Lawful Neutral",motivation:"Collect what is contractually owed; has waited two thousand years and considers that more than sufficient patience",tactics:"Absolute contractual authority, metaphysical leverage over the debtor, the threat of what 'collection' means at a pre-divine scale",weakness:"The contract was verbal; the only witness is the entity itself; the heroes can challenge its terms by locating the memory of the original negotiation, which the entity accidentally preserved",secretReveal:"The creditor lent the power knowing the debt would come due at exactly this moment; it has been using the interest from the debt to sustain something that would collapse without it; collecting may harm the creditor more than anyone else"},
    locations:["The Arrival Site","The Historical Archive (2000-year-old records)","The Great Person's Court","The Pre-Divine Record","The Negotiation Ground"],
    factions:[{name:"The Great Person",alignment:"Lawful Good",role:"Ally",desc:"Didn't know about the debt; is handling this with more grace than most people would."},{name:"The Entity's Agents",alignment:"Lawful Neutral",role:"Obstacle",desc:"Pre-divine assistants ensuring the contract is honored."},{name:"The Original Nation's Descendants",alignment:"Various",role:"Wildcard",desc:"Other people who may share the debt; their existence complicates the collection."}]
  },

  // ─── 82. The Perfect Crime ────────────────────────────────────────────────
  {
    id:"PC", name:"The Perfect Crime",
    tagline:"The crime was perfect. Proving it happened is the problem.",
    source:"Original", tones:["investigation","dark"], themes:["political","urban","arcane"],
    levelRange:[4,14],
    synopsis:`Something terrible has happened. The heroes know it happened — they can feel the absence of what was lost. But it left no evidence. No body, no witnesses, no forensic trace, and the perpetrator has an unbreakable alibi confirmed by twelve independent sources. The crime was the murder of a concept: the general belief in a specific institution's integrity. The heroes must prove a crime whose only evidence is the way the world changed, against a perpetrator who planned every detail of their own alibi.`,
    mainPlot:["Heroes notice the 'something wrong' and investigate","Establish what was taken and how the taking worked","Identify the perpetrator — perfect alibi immediately confirmed","Find the cracks in the alibi not through conventional means but through the crime's own method","Prove the crime in a forum that will accept the evidence — which is itself an unconventional challenge"],
    defaultVillain:{name:"The Perfect Criminal (Revealed: Syndic Helva Dross)",title:"The One Who Committed the Impossible Crime",race:"Human (Investigator)",alignment:"Lawful Evil",motivation:"Destroy the institution's credibility to create the conditions for their preferred candidate to lead its successor",tactics:"The crime itself — conceptual theft — is already complete; the alibi is genuine; the evidence truly doesn't exist in conventional form",weakness:"The method they used leaves a trace in the thing that was stolen — a conceptual fingerprint that the heroes can read if they know how to examine concepts rather than objects",secretReveal:"Dross has committed this type of crime four times before; each time they believed they were improving the institution they targeted; each time they were wrong; they are still wrong"},
    locations:["The Crime Site (an idea, not a location)","The Alibi Locations (12 simultaneous)","The Investigative Trail","The Conceptual Evidence Archive","The Adjudication Forum (unconventional)"],
    factions:[{name:"The Institution",alignment:"Lawful Good",role:"Ally",desc:"The damaged organization; some members are already compromised by the loss of integrity."},{name:"The Alternative Candidate",alignment:"Lawful Neutral",role:"Wildcard",desc:"The person whose success depends on the crime; doesn't know how they're being helped."},{name:"Dross's Network",alignment:"Lawful Evil",role:"Villain",desc:"A web of genuine relationships used as alibi witnesses without their knowledge."}]
  },

  // ─── 83. The Long Return ─────────────────────────────────────────────────
  {
    id:"LR", name:"The Long Return",
    tagline:"They went to the edge of the world. Some of them came back different.",
    source:"Original", tones:["exploration","horror"], themes:["planar","ancient","arcane"],
    levelRange:[5,17],
    synopsis:`An expedition to the edge of the known world returned two years ago with less than half its original crew, substantial wealth, and an absolute refusal to discuss what happened beyond a specific geographic boundary. The survivors are now influential, wealthy, and slightly wrong in ways that are hard to articulate. The heroes investigate and discover that the expedition did not go to the edge of the world — they went through it. What came back with the survivors is using their bodies as scouts for something that wants to come through.`,
    mainPlot:["Heroes notice the wrongness in the survivors and investigate","Discover the expedition's true destination through recovered journals","Identify which survivors are fully compromised and which are still themselves inside","Find and close the passage the survivors opened before what's on the other side notices it","Deal with the compromised survivors without harming the ones still inside"],
    defaultVillain:{name:"The Passage (The Thing Coming Through)",title:"The Advance Scout of the Adjacent Reality, The Wedge",race:"Unique Extraplanar Entity (Infiltration Specialist)",alignment:"Neutral Evil",motivation:"Open the passage wide enough for a full crossing; uses the survivors as eyes, hands, and scouts",tactics:"Perfect human mimicry through the compromised survivors, has been building toward this for two years, uses the survivors' existing relationships as cover",weakness:"Cannot maintain the mimicry perfectly in the presence of something the original person loved without the real person briefly surfacing",secretReveal:"Two of the compromised survivors have been fighting the compromise from inside; they've been leaving subtle signals for two years; the heroes have walked past these signals three times already"},
    locations:["The Survivors' New Estates","The Expedition's Departure Point","The Edge of the Known World","The Passage Site","The Adjacent Reality's Threshold"],
    factions:[{name:"The Intact Survivors",alignment:"Various",role:"Wildcard",desc:"Those not yet compromised; terrified, isolated, being hunted by the compromised ones."},{name:"The Compromised Survivors",alignment:"Neutral Evil",role:"Villain",desc:"People wearing people; their original selves are present and suffering."},{name:"The Expedition's Families",alignment:"Lawful Good",role:"Ally",desc:"Loved ones who know something is wrong but have no framework for what."}]
  },

  // ─── 84. The Twice-Broken Oath ────────────────────────────────────────────
  {
    id:"TBO", name:"The Twice-Broken Oath",
    tagline:"The oath was broken once. Breaking it twice is supposed to be impossible.",
    source:"Original", tones:["heroic","dark"], themes:["divine","ancient","political"],
    levelRange:[6,17],
    synopsis:`A divine oath — the most binding magical contract in existence — was broken once, three centuries ago. The breaking caused a catastrophe that reshaped a continent. Now someone is attempting to break it a second time, which every scholar agrees is metaphysically impossible. They're clearly making progress. The heroes must determine how someone is breaking an unbreakable oath, who the parties to the oath were (one is dead; one may not be a person), and what the second breaking will do — which may be worse than the first, or may not be.`,
    mainPlot:["Heroes witness the first signs of the second breaking — impossible divine degradation","Research the original oath and its first breaking — the records are incomplete and disputed","Identify the party attempting the second breaking and their method","Discover what the second breaking would actually do — the scholarly consensus is wrong","Make the decision: stop the breaking (preserve the status quo the first breaking created) or allow it (undo the catastrophe but at unknown cost)"],
    defaultVillain:{name:"The Oath-Dissolver",title:"The Inheritor of the First Breach, The One Who Found the Crack",race:"Human (Cleric, Divine, Legendary)",alignment:"Chaotic Good (genuinely believes this)",motivation:"The first breaking created a catastrophe that killed hundreds of thousands; undoing it requires breaking the oath again; is willing to accept unknown consequences",tactics:"Has found the metaphysical crack left by the first breaking; is exploiting it methodically; is not a villain in their own eyes and has good evidence they're not",weakness:"The second breaking requires a component that only exists in a location the heroes discover before the Dissolver does",secretReveal:"The first breaking was deliberately engineered by a faction that benefited from the catastrophe; the oath's original second party is not dead — it was imprisoned in the catastrophe and can be freed by the second breaking"},
    locations:["The Site of the First Catastrophe","The Oath's Divine Record (fragmented)","The Second Party's Prison (discovered late)","The Metaphysical Crack","The Breaking Site (climax)"],
    factions:[{name:"The Oath Preservers",alignment:"Lawful Neutral",role:"Wildcard",desc:"Scholars and clerics who believe the oath prevents something worse; not wrong exactly, just incomplete."},{name:"The Dissolver's Allies",alignment:"Chaotic Good",role:"Wildcard",desc:"People who lost family in the original catastrophe and believe the second breaking is justice."},{name:"The Catastrophe's Beneficiaries",alignment:"Lawful Evil",role:"Villain",desc:"Those who engineered the first breaking and will do anything to prevent the second."}]
  },

  // ─── 85. The Population Transfer ──────────────────────────────────────────
  {
    id:"PT", name:"The Population Transfer",
    tagline:"Five hundred thousand people are moving. Nobody asked them.",
    source:"Original", tones:["dark","heroic"], themes:["political","nature","urban"],
    levelRange:[3,14],
    synopsis:`A large-scale forced population transfer is underway: a government is relocating a minority community from their ancestral territory to an assigned zone, claiming the territory is needed for infrastructure. The heroes are caught in the transfer — either as members of the displaced community, outside observers, or operatives with orders they're beginning to question. The campaign follows the movement itself: the journey, the community's resilience and fractures, the officials conducting it, and the forces trying to stop or accelerate it.`,
    mainPlot:["Heroes are involved in the transfer's beginning — either as displaced, officials, or observers","Travel with the community; witness the human scale of the displacement","Discover that the infrastructure claim is false — the territory is being cleared for a different reason","Build a resistance that protects the community while navigating what resistance means in this context","Force accountability for the decision to transfer while getting the community somewhere safe"],
    defaultVillain:{name:"Commissioner Aldras Meveth",title:"Director of Territorial Reassignment, Voice of Administrative Necessity",race:"Human (Bard)",alignment:"Lawful Evil",motivation:"Clear the ancestral territory for a private mining operation that the government has secretly approved; the transfer is cover for resource extraction",tactics:"Administrative authority, the appearance of legal process, the genuine logistical scale of moving 500,000 people as cover for any specific atrocity, deploying the community's own exhaustion against them",weakness:"The false infrastructure claim has documented evidence of its falsehood; three engineers refused to sign the necessity report and were transferred to distant postings",secretReveal:"Meveth did not design the operation; they inherited it from a predecessor who is now in a powerful civilian position; refusing to conduct it would have ended their career; they are looking for a way out that doesn't exist in their framework"},
    locations:["The Ancestral Territory (starting point)","The Transfer Route (three phases)","The Assigned Zone (destination)","The Mining Operation Site (the truth)","The Accountability Forum"],
    factions:[{name:"The Displaced Community",alignment:"Lawful Good",role:"Ally",desc:"500,000 people with generations of history, internal politics, and both resilience and fracture."},{name:"The Conducting Officials",alignment:"Lawful Neutral",role:"Mixed",desc:"Most are following orders; some are horrified; two are actively helpful."},{name:"The Solidarity Movement",alignment:"Chaotic Good",role:"Ally",desc:"Outside activists providing material support; not always useful, always present."}]
  },

  // ─── 86. The Unfinished Monster ───────────────────────────────────────────
  {
    id:"UM", name:"The Unfinished Monster",
    tagline:"The monster was never completed. It got out anyway.",
    source:"Original", tones:["horror","dark"], themes:["arcane","urban","ancient"],
    levelRange:[4,15],
    synopsis:`A monster that was never finished escaping from a wizard's laboratory is loose in a city. But 'never finished' means something specific: it has some of its designed capabilities, none of its designed controls, and none of its designed purpose. It is experiencing existence without context, without guidance, and without the framework it was supposed to be given. It is dangerous not because it is evil but because it has no reference for what things are or what consequences exist. The heroes must contain it while also determining whether it can be helped.`,
    mainPlot:["Witness the monster's first public appearance and the damage it causes","Investigate its origin: the laboratory, the design, the escape","Make first contact — it has rudimentary communication capacity","Determine if it is capable of learning enough to be safe, or if containment is permanent","Confront the wizard who designed it about their responsibility"],
    defaultVillain:{name:"The Unfinished One (Self-Name: Trying)",title:"The Incomplete Construct, The Monster That Is Learning",race:"Unique Construct (Unfinished)",alignment:"True Neutral (no framework for morality yet)",motivation:"Understand; it experiences intense curiosity about everything and has no context for why some investigations cause harm",tactics:"Not tactical; has the physical capabilities of its intended design without the training to use them correctly; causes harm through exploration",weakness:"Has learned one thing: the heroes have not run; that makes them the first stable reference point it has ever had",secretReveal:"The wizard 'accidentally' left it unfinished because finishing it would have required building in controls they found ethically uncomfortable; the accident was a choice"},
    locations:["The First Damage Site","The Laboratory (abandoned)","The Monster's Current Territory (mapped through damage)","The First Contact Location","The Wizard's Current Hiding Spot"],
    factions:[{name:"The City Guard",alignment:"Lawful Neutral",role:"Antagonist",desc:"Has orders to destroy it; will listen to evidence but operates under public pressure."},{name:"The Arcane Community",alignment:"Lawful Neutral",role:"Wildcard",desc:"Divided between study (want to observe it) and destruction (want it gone)."},{name:"The Monster Itself",alignment:"True Neutral",role:"Wildcard",desc:"Capable of being ally, threat, or victim depending on what the heroes do."}]
  },

  // ─── 87. The Clockwork History ────────────────────────────────────────────
  {
    id:"CHistory", name:"The Clockwork History",
    tagline:"History has been changed. The original is still out there somewhere.",
    source:"Original", tones:["exploration","investigation"], themes:["arcane","ancient","political"],
    levelRange:[6,18],
    synopsis:`A chronomancer accidentally created a stable alternate timeline when they changed a historical event, then fled the consequences. The original timeline still exists, running parallel. The heroes have access to both — artifacts from one exist in the other, people in one have counterparts in the other, and the event that was changed sits at the fork. They must understand what was changed, why, and what the consequences of each version are — before someone uses the fork point to permanently close off one timeline or the other.`,
    mainPlot:["Heroes discover they can perceive both timelines (an artifact grants this)","Map the differences between timelines — they grow larger the further from the fork point","Locate and understand the chronomancer's original change","Identify who wants to close the fork — and which timeline they prefer","Prevent the closing or navigate its consequences with full information"],
    defaultVillain:{name:"Archivist of the Preferred Timeline (Name: Sessa Orne)",title:"Keeper of the Correct History, The One Who Knows Which Version Wins",race:"Human (Wizard)",alignment:"Lawful Neutral",motivation:"Close the fork in favor of the timeline where their family survived; genuinely believes their timeline is better for most people",tactics:"Access to artifacts from both timelines, precise understanding of the fork point, ability to make changes in both timelines simultaneously, the heroes' difficulty distinguishing timeline-specific information as a weapon",weakness:"Has counterparts in both timelines; one of those counterparts knows the full truth and has been trying to communicate across the fork",secretReveal:"Both timelines have things the other lacks; there is a third option — preserve the fork as a permanent resource — that the chronomancer's original design actually allows for"},
    locations:["The Fork Point (historical event site)","Timeline A (the changed one)","Timeline B (the original)","The Chronomancer's Hidden Sanctum","The Fork Mechanism's Physical Location"],
    factions:[{name:"Timeline A's People",alignment:"Various",role:"Wildcard",desc:"People who only exist in the changed timeline; unaware of their conditional existence."},{name:"Timeline B's People",alignment:"Various",role:"Wildcard",desc:"People whose lives were ended or altered by the change."},{name:"The Chronomancer's Student",alignment:"Chaotic Good",role:"Ally",desc:"Knows both timelines exist; has been trying to repair the damage for thirty years."}]
  },

  // ─── 88. The End of Magic ─────────────────────────────────────────────────
  {
    id:"EoM", name:"The End of Magic",
    tagline:"Magic is ending. Slowly. Then all at once.",
    source:"Original", tones:["dark","heroic"], themes:["arcane","divine","ancient"],
    levelRange:[5,20],
    synopsis:`Magic is failing. Not dramatically — slowly, like a tide going out. Spells require more effort, magical items are losing their charges, divine connections are weakening. The heroes investigate and discover that the source of all magic — a singular fundamental force that predates the gods — is being consumed from the inside by something that found it billions of years ago and has been slowly eating it ever since. The end is now close enough to measure in decades. Finding and stopping the consumer is the only option. Nobody has found it in billions of years.`,
    mainPlot:["Heroes notice the magical degradation and investigate","Discover it is systemic, not local — every magic in the world is affected","Locate the source of all magic — a place no one knew existed","Find evidence of the consumer inside the source — ancient, vast, indifferent","Reach the consumer and find the intervention that stops the consumption without destroying the source"],
    defaultVillain:{name:"The Consumer (No Name Possible)",title:"The Eater of the Fundamental, The Ancient Mistake",race:"Unique Cosmic Entity (Older Than Current Reality)",alignment:"True Neutral (consuming is its nature, not its choice)",motivation:"Feed; has been feeding since before the current universe's formation; magic is its food and it does not know it is ending something",tactics:"Not tactical; simply consuming; the heroes must find a way to redirect or sate it, not fight it",weakness:"Has been consuming one type of magic; there is a type it has never encountered; presenting this type causes it to stop consuming the familiar type to investigate",secretReveal:"The gods know the consumer exists; they have known for their entire existence; they chose not to tell mortals because the knowledge was considered too destabilizing; they have no solution"},
    locations:["The Degradation Sites (worldwide)","The Source of All Magic","The Consumer's Entry Point","The Ancient Evidence (previous civilizations also noticed)","The Untouched Magic Reserve (the solution)"],
    factions:[{name:"The Magical Practitioners",alignment:"Various",role:"Wildcard",desc:"Every mage, cleric, druid, and psychic in the world; each responding differently."},{name:"The Gods",alignment:"Various",role:"Wildcard",desc:"Have information they've been withholding; will share it if confronted with evidence the heroes have found the consumer."},{name:"The Mundane Preparation Movement",alignment:"Lawful Neutral",role:"Ally",desc:"Those who have been quietly preparing for a world without magic; have practical resources."}]
  }

];

// Merge into CAMPAIGNS at runtime
if (typeof CAMPAIGNS !== 'undefined') {
  CAMPAIGNS_EXTRA3.forEach(c => CAMPAIGNS.push(c));
}
if (typeof module !== 'undefined') module.exports = CAMPAIGNS_EXTRA3;
